if ENV['COVERAGE']
  require 'simplecov'

  SimpleCov.start do
    add_filter '/spec/'
  end
end

require 'bundler'
Bundler.require(:default, :test)

$:.unshift(File.dirname(__FILE__) + '/../lib')

# Requires supporting files with custom matchers and macros, etc,
# in ./support/ and its subdirectories.
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each {|f| require f}

# silence deprecation warning
require 'i18n'
I18n.enforce_available_locales = true

require 'redis'
require 'moneta'
require 'influxdb'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.around(:each, :redis => true) do |example|
    Sandstorm.redis = ::Redis.new(:db => 14)
    Sandstorm.redis.flushdb
    example.run
    Sandstorm.redis.quit
  end

  config.around(:each, :influxdb => true) do |example|
    Sandstorm.influxdb = InfluxDB::Client.new 'sandstorm_test',
      :username => 'sandstorm', :password => 'sandstorm', :retry => false
    Sandstorm.influxdb.query('DELETE FROM /.*/')
    example.run
  end

  config.around(:each, :moneta => true) do |example|
    Sandstorm.moneta = ::Moneta.new(:Memory)
    example.run
    Sandstorm.moneta.clear
    Sandstorm.moneta.close
  end

  config.after(:each, :time => true) do
    Timecop.return
  end

end
